; Inno Setup script — GrayBar Meraki Manager
; Produces: Output\GrayBarMerakiManager-Setup.exe
; Generated by build.bat — do not run this directly, use build.bat instead.

#define AppName      "GrayBar Meraki Manager"
#define AppExeName   "GrayBarMerakiManager.exe"
#define AppPublisher "GrayBar"
#define AppVersion   "2.0.0"
#define AppURL       ""
#define SourceDir    "dist\GrayBarMerakiManager"

[Setup]
AppId={{A3F7B2C1-4D89-4E6F-9ABC-123456789DEF}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
PrivilegesRequired=admin
OutputBaseFilename=GrayBarMerakiManager-Setup
OutputDir=Output
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
WizardSmallImageFile=
; Installer look
SetupIconFile=
UninstallDisplayName={#AppName}
UninstallDisplayIcon={app}\{#AppExeName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional icons:"; Flags: checked

[Files]
; Bundle the entire PyInstaller output folder
Source: "{#SourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; Start Menu shortcut
Name: "{group}\{#AppName}";     Filename: "{app}\{#AppExeName}"
Name: "{group}\Uninstall";      Filename: "{uninstallexe}"
; Desktop shortcut (only if user ticked the task above)
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon

[Run]
; Offer to launch the app immediately after install
Filename: "{app}\{#AppExeName}"; \
    Description: "Launch {#AppName} now"; \
    Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Clean up the logs folder created at runtime
Type: filesandordirs; Name: "{app}\logs"

[Code]
// Verify Windows 11 / Windows 10 minimum requirement
function InitializeSetup(): Boolean;
var
  Version: TWindowsVersion;
begin
  GetWindowsVersionEx(Version);
  if (Version.Major < 10) then
  begin
    MsgBox('GrayBar Meraki Manager requires Windows 10 or later.', mbError, MB_OK);
    Result := False;
  end
  else
    Result := True;
end;
